---
- name: Delete AWS ec2
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Find an amazon EC2 instance id from name
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
          tag:Name: "{{ aws_name }}"
      register: ec2
    
    - name: Delete an amazon EC2 instance
      amazon.aws.ec2_instance:
        state: absent
        region: "{{ region }}"
        instance_ids: "{{ ec2.instances[0].instance_id  }}"
        wait: true
    
    
    