- name: Configure instance(s)
  hosts: running
  become: true
  remote_user: root
  tasks:
    - name: Install Apache on CentOS/Red Hat
      package:
        name: 
          - httpd
          - firewalld
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install Apache on Debian/Ubuntu
      package:
        name: 
          - apache2
          - firewalld
        state: present
      when: ansible_os_family == 'Debian'
      
    - name: Start Firewalld service
      service:
        name: firewalld
        enabled: true
        state: started
      when: ansible_os_family == 'RedHat'

    - name: Start Firewalld service
      service:
        name: firewalld
        enabled: true
        state: started
      when: ansible_os_family == 'Debian'

    - name: Firewall permits access to httpd service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: Start Apache service
      service:
        name: httpd
        enabled: true
        state: started
      when: ansible_os_family == 'RedHat'
